origin: [ 0.0, 0.5207 ]

solver:
  interiorPoints: 20
  maxVoltageElbow: 6
  maxVoltageWrist: 5
  maxVoltageLift: 6
  maxAccelerationElbow: 1.5
  maxAccelerationWrist: 1.4
  maxAccelerationLift: 1.2
  maxJerk: 1

lift:
  mass: 1.0 # estimated
  minHeight: 0.01
  maxHeight: 0.66
  motor:
    type: neo
    count: 3
    reduction: 63.75

elbow:
  mass: 1.374
  length: 0.9144
  cgRadius: 0.52
  moi: 0.1427
  minAngle: -1.0472 # -60 degrees
  maxAngle: 4.1015 # 235 degrees
  motor:
    type: neo
    count: 3
    reduction: 53.125

wrist:
  mass: 2.372
  length: 0.2921
  cgRadius: 0.16 # estimated
  moi: 0.0435
  minRelAngle: -1.5707
  maxRelAngle: 3.1415
  motor:
    type: neo
    count: 1
    reduction: 42.222

constraints:
  floor:
    type: minY,
    point: end
<<<<<<< HEAD
    args: [ 0 ]
  heightLimit:
    type: maxY
    point: end
    args: [ 1.98 ]
  robotBody:
=======
    args: [ 0.2 ]
  robotFrameWrist:
>>>>>>> 8254ce48bc85e1499057e0bec71508329d9e6532
    type: rectangle
    point: wrist
    args: [
      -0.2, 0,
      0.2, 1.5 # experimental constraint
    ]
  robotFrameEnd:
    type: rectangle
    point: end
    args: [
      -0.2, 0,
      0.2, 1.5 # experimental constraint
    ]
